### ISSUE TITLE
Scripting API doesn't set Main.Feature Toggles.Multi FPGA

### ISSUE THREAD

**Issue by buckd** [ni/niveristand-engine-simulation-toolkit-custom-device#52]
The `Main.Feature Toggles.Multi FPGA` property was added to the system definition late in order to prevent us from having to set the feature toggle each time we wanted to load a test. However, it's not in the scripting API, which means when you script a new custom device, deployment fails. You have to manually open the sysdef to get mutation code to run and then save. Now everything will deploy.

**Comment by rtzoeller** [comment]
One thing to note: the scripting api only supports the multi-fpga use case, so we should always set this flag, instead of reading from the ini file.

**Comment by rtzoeller** [comment]
I had debated the merits of it before given that we can unit test the scripting individually, but I can see value in adding a system test which scripts a sysdef and then immediately deploys it. That would be good to add as part of this change.
