### ISSUE TITLE
Inconsistent background opacity for icons

### ISSUE THREAD

**Issue by rtzoeller** [ni/niveristand-engine-simulation-toolkit-custom-device#54]
The icons in the system explorer have inconsistent backgrounds; some are white, while others are transparent. The icons with white backgrounds appear different than the native VeriStand ones when highlighted.

![image](https://user-images.githubusercontent.com/573497/52976841-b23a8e80-3390-11e9-95b5-bc6feba3207e.png)

**Comment by Karl-G1** [comment]
Low impact and minor issue. Closing this one.
